# Generated by Django 3.2.4 on 2021-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_auto_20211109_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='passs',
        ),
        migrations.AddField(
            model_name='people',
            name='pwd',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
