# Generated by Django 3.2.9 on 2021-12-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_auto_20211126_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('clusterName', models.CharField(max_length=100)),
                ('depth', models.CharField(max_length=100)),
                ('strategy', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
            ],
        ),
    ]
