# Generated by Django 3.2.9 on 2021-12-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0007_alter_crawlingqueue_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('clustername', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='crawlingqueue',
            name='strategy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
