# Generated by Django 3.2.9 on 2021-12-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0007_alter_crawlingqueue_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlingqueue',
            name='strategy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
