# Generated by Django 3.2.9 on 2021-12-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_auto_20211220_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
        ),
    ]
